#!/usr/bin/env python3
"""
_snapshot_final.py — Sprint cycle diff snapshot for handover docs.

Reads relevant.json + shared/tenders.json and prints a structured
coverage report to stdout (Markdown table format).

Usage:
    python scripts/_snapshot_final.py > docs/FINAL_SPRINT_CYCLE_DIFF.md
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).parent.parent
REL = ROOT / "data" / "filtered" / "relevant.json"
SHARED = ROOT.parent.parent / "shared" / "tenders.json"


def _source(notice: dict) -> str:
    tid = str(notice.get("tender_id", ""))
    src = notice.get("_source") or notice.get("source", "")
    if src:
        return src
    if tid.startswith("AU-TEN"):
        return "AU-TEN"
    if "-" in tid and tid.split("-")[0].isalpha():
        return tid.split("-")[0]
    return "TED"


def main() -> None:
    rel = json.loads(REL.read_text(encoding="utf-8"))
    tenders = json.loads(SHARED.read_text(encoding="utf-8")) if SHARED.exists() else []

    sources: dict[str, int] = defaultdict(int)
    countries: dict[str, int] = defaultdict(int)
    for n in rel:
        sources[_source(n)] += 1
        cc = n.get("_country_normalized") or n.get("country", "Unknown")
        countries[cc] += 1

    has = {
        "_framework_type":     sum(1 for n in rel if n.get("_framework_type")),
        "_authority_id":        sum(1 for n in rel if n.get("_authority_id")),
        "_strategy_a_specs":    sum(1 for n in rel if n.get("_strategy_a_specs")),
        "_extracted_specs":     sum(1 for n in rel if n.get("_extracted_specs")),
        "_contract_type":       sum(1 for n in rel if n.get("_contract_type")),
        "award.awarded":        sum(1 for n in rel if isinstance(n.get("award"), dict) and n["award"].get("awarded")),
        "title_en":             sum(1 for n in rel if n.get("title_en")),
        "description_en":       sum(1 for n in rel if n.get("description_en")),
        "_qty_mined":           sum(1 for n in rel if n.get("_qty_mined")),
        "_deadline_mined":      sum(1 for n in rel if n.get("_deadline_mined")),
    }

    total = len(rel)

    print("# Final Sprint Cycle Diff — Handover State 2026-05-19")
    print()
    print("> Auto-generated by `scripts/_snapshot_final.py`.")
    print()
    print("## Pipeline Volumes")
    print()
    print(f"| Dataset | Count |")
    print(f"|---------|------:|")
    print(f"| `relevant.json` notices | {total} |")
    print(f"| `shared/tenders.json` (post safety-net) | {len(tenders)} |")
    print(f"| Dropped by 14j safety-net | {total - len(tenders)} |")
    print()
    print("## Source Breakdown (`relevant.json`)")
    print()
    print("| Source | Notices |")
    print("|--------|--------:|")
    for k, v in sorted(sources.items(), key=lambda x: -x[1]):
        print(f"| `{k}` | {v} |")
    print()
    print("## Country Breakdown (top 15)")
    print()
    print("| Country | Notices |")
    print("|---------|--------:|")
    for k, v in sorted(countries.items(), key=lambda x: -x[1])[:15]:
        print(f"| {k} | {v} |")
    print()
    print("## Field Coverage (`relevant.json`)")
    print()
    print("| Field | Count | % |")
    print("|-------|------:|--:|")
    for field, count in has.items():
        pct = f"{count / total * 100:.0f}%"
        print(f"| `{field}` | {count} | {pct} |")
    print()
    print("## Sprint Window Contributions")
    print()
    print("| Window | Sprint | Key Deliverable | Impact |")
    print("|--------|--------|-----------------|--------|")
    print("| A | 14a | UK-FTS adapter, dedup fix | +6 UK notices |")
    print("| B | 14b–d | UA adapter, award-match LLM (Haiku, F1=1.0), TR retired | +2 UA, better awards |")
    print("| C | 14e–h | TED-XML backfill (buyer URLs, refs), CZ adapter hardening | +89% buyer_profile_url TED |")
    print("| D | 14i–m | Text-mining (3k), contract-type (3j), value-inference rollback, 14j hardening | +316 contract_type |")
    print("| E | 14n | Strategy A (proactive DE/PL/CZ scraping), AU-ATM adapter, TED Quick-Wins | +3 strategy_a_specs |")
    print()
    print("## Sprint E (Window E) — Strategy A Detail")
    print()
    sa_tenders = [t for t in tenders if t.get("strategy_a_specs")]
    print(f"Tenders with `strategy_a_specs` in `shared/tenders.json`: **{len(sa_tenders)}**")
    print()
    for t in sa_tenders:
        sa = t["strategy_a_specs"]
        tt = sa.get("trailer_types", [])
        conf = sa.get("confidence", "?")
        print(f"- `{t['id']}` — {t.get('title', 'N/A')[:60]} | confidence={conf} | types={len(tt)}")
    print()
    print("## Deferred to Window F")
    print()
    print("| Item | Reason |")
    print("|------|--------|")
    print("| Playwright-based DE/CZ PDF download | evergabe login-wall + VOP JS wrapper |")
    print("| CZ eIDAS certificate auth | Out-of-scope; `auth_risk=eidas` graceful skip active |")
    print("| AU-ATM merge into relevant.json | Smoke OK (18 hits), merge pending |")
    print("| NSPA full run | Manual trigger only; 5 s throttle per page |")
    print("| EE/LT/GR adapter completion | XHR discovery open |")
    print("| Frontend strategy_a_specs rendering | Schema ready; UI not built |")


if __name__ == "__main__":
    main()
